# Generated by Django 4.1 on 2022-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalentry_text', models.CharField(max_length=200)),
                ('entry_date', models.DateTimeField(verbose_name='entry date')),
            ],
        ),
    ]
