# Generated by Django 4.1.3 on 2022-12-04 17:42

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_journalentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sensitive_data',
            field=django_cryptography.fields.encrypt(models.CharField(default='hello', max_length=10)),
        ),
    ]
